[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.18"
  TZ = "Asia/Kolkata"

[context.production.environment]
  HUGO_VERSION = "0.100.2"
  HUGO_ENV = "production"
